{{ if .Values.coreOnlyRelease }}
apiVersion: v1
kind: Secret
metadata:
  name: node-corekeys
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
type: Opaque
data:
  kes.skey: |
    dHlwZTogU0tleUVTIFRQcmFvc1N0YW5kYXJkQ3J5cHRvCnRpdGxlOiBLRVMgU2lnbmluZyBLZXkK
    Y2Jvci1oZXg6CiA1OTAyYzAxNTM0NTlkMzRjOTE4N2YyYzdlMzE1NGZiZWVjYWU3NzgxYTJmMzdk
    ZmQ2NjY1ZDFkZTQ4ZjQ3N2M2OGIyNjMzMTJlY2U3NDgyYgogNTA5MDIwNzEzZDNjNTg1MzI5NmQ3
    YTY4ZmJmZWRjYzg5NDY4N2VhYzYyZmFhNzY1Y2FmYTI4YmYzMDI2OGVmZTliZWIzNThhYWVkZjA2
    NzQKIDYwY2EyMDVjNWE4NDUyYmEyM2EzNWUwZGNkMTVhZTI4ZDUzMzkyMDM3YWJhYTJmOTU0MmNh
    MWM5OTc5YzFlNjEzOTI3ZDBlZGZjYWFlMWIxCiAyYzFiMzdkZDI5OGEyMTgzNzg4ZGIzYmRmYzI1
    MTQwYTM5MWRiYTE0NDhkOTFjYTY2ZGNkODUyMjg4NmU2NDU4YzEyMjViM2ViYzQwZWNmMAogZGUz
    NzE4MjdlZjlkYzA1OGE0OTAzNDM3Y2I3OTMzMDk1NjYxYmRiZTE1Y2Y4MDhjNzY2NzYzZjM5MDQ3
    M2JjODczNzQzMzk3MjNmOWVlMmEKIDQzZTcxNDZiMWM5NzZhZWNiNGIxNTczYTgwMjcwYmM2OThm
    MjIyNTY2OTQxZWI4YjhlMmM5ZjE4ZWUwNmVlOGRmOWQ1YWNiMDlkNzM2MjkyCiAzMWQ4ZTMzMDll
    MjliMTAwNDc1MDE3Njc0ZDdjM2YyZDk4MmJjOGJkMTkzOGM1N2UzMTQyNTEwNjdiOWMxMzRiMTQ4
    MTg0MGFkODA2YWQ4MAogZmE3MGExMjgwOGVkZGU4NGVhMDA5MTNkNjE1NWQyZWE2ZGNiNTg4MjA5
    MTg0MGFkODA2YWQ4MAogZmE3MGExMjgwOGVkZGU4NGVhMDA5MTNkNjE1NWQyZWE2ZGNiNTg4MjA5
    MTg0MGFkODA2YWQ4MAogZmE3MGExMjgwOGVkZGU4NGVhMDA5MTNkNjE1NWQyZWE2ZGNiNTg4MjA5
    OWE3Zjk4CiA0Y2FkNTAwNDQyNjI3ZDY4ZWY5YmYzYjAwMDUyZDI3ZDhkMDY4NzA2OGQxM2FmMjg4
    MTg0MGFkODA2YWQ4MAogZmE3MGExMjgwOGVkZGU4NGVhMDA5MTNkNjE1NWQyZWE2ZGNiNTg4MjA5
    MTg0MGFkODA2YWQ4MAogZmE3MGExMjgwOGVkZGU4NGVhMDA5MTNkNjE1NWQyZWE2ZGNiNTg4MjA5
    IDQzZGRlMmFmMDQ5YjE1ODlkYmQ1NWY2MWI4OTNjZDBjNGE0YTViNDU1ODg3ZTdlZjliNjc5MDYz
    MzZjZTU0NTAxMzFlN2M4NWQxNmRmZWNkCiBhODljYzYyZGE4ZWY4MzhhNmM1ZmE0Y2ZhZDE2Y2E0
    MTUzMTQxNjdkMjJlOTgwYWZhZTA5ZmRjMWRkZjIzYWYyNjg5OTYxZTdmM2JjMTE3NgogNzA4MDc3
    MzNmMTdlM2EyZDVjOTg1ZWI4MmNiMDQ5ZTkxMTZlNmFlYWI5YTM5NDUyMmQzNzU4M2Y3NzllYzc2
    YzJkOGU5YWE0ZmY5MWY4ZGYKIDIyYTk0OWRmNmI3ZGRkOGM3YzNjMDJmY2Q2MzY3OTI3OTAzY2E0
    NTE0M2NlMDlmZTcwNTM2MzFhN2U5MDdiZmYwY2EwMzQ0YTVjZjM2ODZmCiA0OTVhOTUwN2MzZDM3
    ZjU2MzAwZGEyMWJkNTAzN2Q4Y2MxZTkxMTcxNWQwYmY0YjMwYjc2ODE1MWEzODNiYjBlYmNhNjcy
    NTlhZDQ3ZjMzNQogMWEwOWU2YzgzNzUxMmMxNGJiOWU4MmViNDYwMzdjNmViNzY3MzdlNWI0NmJh
    Y2Q3NjhjMjU0NDY3Y2M0ZmFmNWJhODdkNGIyMWUwZGM2NjUKIDNjZTNjYzc4MmZjNjk2MTVhOTM0
    Y2M2OGU5ZjRkMjk5MGIyYTUwMDgyZjliOWQ2NjU3MjcxMAo=
  op.cert: |
    dHlwZTogTm9kZSBvcGVyYXRpb25hbCBjZXJ0aWZpY2F0ZQp0aXRsZTogCmNib3ItaGV4OgogODI4
    MTg0MGFkODA2YWQ4MAogZmE3MGExMjgwOGVkZGU4NGVhMDA5MTNkNjE1NWQyZWE2ZGNiNTg4MjA5
    MTg0MGFkODA2YWQ4MAogZmE3MGExMjgwOGVkZGU4NGVhMDA5MTNkNjE1NWQyZWE2ZGNiNTg4MjA5
    MTg0MGFkODA2YWQ4MAogZmE3MGExMjgwOGVkZGU4NGVhMDA5MTNkNjE1NWQyZWE2ZGNiNTg4MjA5
    ZGIwYmY0NjY4NTMzNDM2MzhhZGUwZGMxYjgwODU2ZWNjNWE0YmEwMTU4MjBkZDM0OTkxMGVlOTFh
    OGMyZDcxNjM3MDRhMwogM2MzMDZkZjJkOWQ4YjY0NmJiMmQyOTZkOTJhZDE4YjJhMzU3ZmQK
  vrf.skey: | 
    dHlwZTogU2lnbktleVZSRiBQcmFvc1ZSRgp0aXRsZTogVlJGIFNpZ25pbmcgS2V5CmNib3ItaGV4
    dHlwZTogU2lnbktleVZSRiBQcmFvc1ZSRgp0aXRsZTogVlJGIFNpZ25pbmcgS2V5CmNib3ItaGV4
    N2JhNGM0YWNjMGFkNzFiZmMwYThjNTYK
{{ end }}