{
 "title": "All Cardano Stake Pools",
 "description": "Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Time", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds)"
    }
   ]
  },
  {
   "title": "KES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(avg(cardano_node_ChainDB_metrics_slotNum_int)/3600)"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_epoch_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Remaining KES",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_Forge_metrics_remainingKESPeriods_int",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Pool Performance",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int / cardano_node_metrics_Forge_node_is_leader_int * 100",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "K8s Cluster Health per Worker Node",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk Utilization"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[1h])) * 3600",
     "legendFormat": "1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[1h])) * 3600",
     "legendFormat": "1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_upTime_ns / (3599999999999.971)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_byron_proxy_ChainDB_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Blocks Assigned",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_int",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Blocks Forged",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Rejected blocks since last restart",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int - cardano_node_metrics_Forge_adopted_int",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Last Block Height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_ChainDB_blockNum_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_byron_proxy_ChainDB_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Core node"
    }
   ]
  },
  {
   "title": "Cardano Slot Height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_ChainDB_slotNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Chain Density",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_density_real * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load 1m" },
    { "expr": "node_load5", "legendFormat": "Load 5m" },
    { "expr": "node_load15", "legendFormat": "Load 15m" }
   ]
  },
  {
   "title": "Node current \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Time Synchronization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds",
     "legendFormat": "Est. error(s)"
    },
    { "expr": "node_timex_offset_seconds", "legendFormat": "Offset: Node vs. Ref." },
    { "expr": "node_timex_maxerror_seconds", "legendFormat": "Max. Error (s)" }
   ]
  },
  {
   "title": "Mempool Transactions",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "ScaleSet Instance File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "ScaleSet Instance" }
   ]
  },
  {
   "title": "Node max \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used /(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_ChainDB_metrics_blockNum_int[150s]) *60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node RSS (allocated memory in RAM, in MB)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(cardano_node_metrics_Stat_rss_int*4096)/(1024*1026)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node peak memory allocated (from OS, in MBytes)",
   "type": "graph",
   "description": "Counts only memory that is physically free",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}